# -*- coding: utf-8 -*-
"""select_db

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/19z7i2EmwfYdPdynaTPIsWwi9AWuRVaGy
"""

#!pip install mysql-connector-python

import mysql.connector

connection = mysql.connector.connect(host='localhost',port='3306',user='root',password='password',database='sql_tutorial')
cursor = connection.cursor()

# 取的部門表格所有資料
cursor.execute('SELECT * FROM `branch`;')

records = cursor.fetchall()
for r in records:
    print(r)

cursor.close()
connection.close()